### ISSUE TITLE
Availability for Craft 3

### ISSUE THREAD

**Issue by szczups** [Firstborn/Craft-CMS-Migration-Manager#10]
First of all, let me say congrats on great work, and solid effort bringing this plugin to life. Is there a plan to migrate this plugin to work with upcoming Craft 3?

Cheers, 
Jakub

**Comment by fb-derrick-grigg** [comment]
Thank you. Yes there is a plan for a Craft 3 version.

**Comment by medoingthings** [comment]
Amazing work. This would be very cool to have for Craft 3. Do you have any timeline?

Cheers,
Mark

**Comment by solidevolution** [comment]
@fb-derrick-grigg If there is a plan, do you have a release date? As long as it isn't available for Craft 3, this issues should be "Open", not "Closed".

**Comment by fb-derrick-grigg** [comment]
@solidevolution no set date yet but I would estimate by May at the latest. I have reopened this issue though.

**Comment by fb-derrick-grigg** [comment]
@solidevolution @medoingthings @szczups   https://github.com/Firstborn/Craft-Migration-Manager
