### ISSUE TITLE
Creating a section via a migration automatically creates an entry type

### ISSUE THREAD

**Issue by benface** [Firstborn/Craft-CMS-Migration-Manager#11]
I created a new section in my local environment called Press Articles (`pressArticles` handle), and as always Craft automatically created an entry type in it with the same name and handle. I changed the entry type's name and handle to singular (Press Article, `pressArticle`) as I usually do. Then I created a migration for that section and applied it to my production environment. Everything seems good, but there are now two entry types in the new section in production: `pressArticle` with the fields I defined, and `pressArticles` with no fields that Craft seems to have created automatically.

**Comment by fb-derrick-grigg** [comment]
@benface this has been fixed in the latest commit. Craft apparently automatically creates default entry types when sections are created, which went unnoticed by our tests since the entry type name always matched the default value.
