### ISSUE TITLE
When the Static field option on a Super Table field is enabled, the migration (Entry) fails

### ISSUE THREAD

**Issue by proenca** [Firstborn/Craft-CMS-Migration-Manager#12]
If the SuperTable field has the Static field option enabled, when doing a migration of a **Entry**, the migration fails returning this error:

`Call to a member function getType() on string (/Users/user/site/craft/plugins/migrationmanager/services/MigrationManager_BaseContentMigrationService.php:81)`

**Comment by fb-derrick-grigg** [comment]
@proenca grab the latest update for the fix, Merry Christmas!
