### ISSUE TITLE
SuperTable + Neo relation Entry's migration

### ISSUE THREAD

**Issue by asparkam** [Firstborn/Craft-CMS-Migration-Manager#16]
I have 2 fields: SuperTable and Neo. I need to place SuperTable field inside Neo. Migration of section works well (and it's awesome). But when I try to **Create migration of Entity** and **restore it** - I have success message, **but** all content **SuperTable which was inside of of Neo is disappearing**.

I know may be it looks like crazy using both of these plugins inside each over, but it's very convenient for creating independent elements and reusing them. And I'd love to create more crazy nesting: Neo->Matrix->Supertable->Matrix - it's very powerful. And if Entry's migration manager will be worked in this case - it will be just wonderful.

P.S. all trace logs is clear and have just success messages.

**Comment by fb-derrick-grigg** [comment]
Is it the setting migration that is empty or the content migration?


On Jan 14, 2018, at 10:46 AM, asparkam <notifications@github.com<mailto:notifications@github.com>> wrote:


I have 2 fields: SuperTable and Neo. I need to place SuperTable field inside Neo. It's okay (and it's awesome). But when I try to create a migration, I have a success message, BUT all content.

I know may be it looks like crazy using both of these plugins inside each over, but it's very convenient for creating independent elements and reusing them. And if Entry's migration will be worked - it will be just wonderful.

P.S. all trace logs is clear and have just success messages.

**Comment by asparkam** [comment]
Migration settings always had all data's

I don't know what exactly helped for me, but my actions:
1) I made all fields a new one from: Neo->Supertable to Neo->Matrix->SuperTable, i.e. wrap SuperTable to native Matrix field.
2) Disabled all required fields. Mostly images (Asset fields) that is absent to dest site folder, made errors in previous try.
3) Made migrations by steps: 
    1. All Craft Native fields 
    2. SuperTable fields 
    3. Neo fields 
    4. All need Sections that have Neo and SuperTable fields. 
    5. Migration of Entry's
4) Cleanup database to previous backup before installing Migration Manager of destination site, and reinstall all (SuperTable, Neo, M.Manager).

Some of these changes helped and Entry's content are migrated. Problem solved but I don't know how)

**Comment by fb-derrick-grigg** [comment]
I haven't been able to reproduce this issue and it sounds like it has not happened again for you. I will close for now. One thing I have seen is the cache does need to get cleared out occasionally when a migration error pops up for no reason.

**Comment by asparkam** [comment]
@fb-derrick-grigg it repeated again few hours ago. SuperTable content inside Matrix inside Neo was empty. And also I noticed a new problem. **I can't templating this fields** i.e. field `productSelector `is undefined in template and I can't access them (but partly it have content in Matrix field but it's not accessing too). If I remove this element and create new one - all is working. Also site has locales, but has not localization of this elements. Do you think locale is a problem?
![2018-01-17_021248](https://user-images.githubusercontent.com/30487905/35008051-ea1d2052-fb2d-11e7-880b-287e406b0afb.png)
![2018-01-17_020147](https://user-images.githubusercontent.com/30487905/35008244-69fd73d0-fb2e-11e7-8d9e-db71a26c9b22.png)

P.S. Yes, cache clearing it's first weapon every time.

**Comment by asparkam** [comment]
@fb-derrick-grigg I try 1.0.8.2 now. It's still repeating(

**Comment by asparkam** [comment]
@fb-derrick-grigg I compared two databases and all SuperTable blocks table is empty and no content. This is main reason why content is undefined.

![no_data1](https://user-images.githubusercontent.com/30487905/35052074-43bdb454-fbd9-11e7-987d-c31d48496f77.png)
![no_data2](https://user-images.githubusercontent.com/30487905/35052075-43e7ab9c-fbd9-11e7-8e85-1ad7a33e4f8f.png)


P.S. JSON-object in generated migration file is valid and has all contents. Content just not inserted into tables.

**Comment by si-em** [comment]
I've also stumbled upon this issue lately. Migrations usually work as expected, except when a Neo field is involved, and all content in said Neo field is deleted after a migration.

Did you find any solution to this?

_EDIT:_ I think this issue should be reopened, by the way :)
_EDIT 2:_ I'm creating a separate issue #28 since mine doesn't involve Supertable etc.
