### ISSUE TITLE
Asset Sources and Sections tabs both show sections

### ISSUE THREAD

**Issue by asparkam** [Firstborn/Craft-CMS-Migration-Manager#18]
In release 1.0.8.2 grouping by tabs show the same field list on two different tabs.

![2018-01-17_152941](https://user-images.githubusercontent.com/30487905/35033091-f0c14776-fb9b-11e7-811a-d79391d3a038.png)
![2018-01-17_152927](https://user-images.githubusercontent.com/30487905/35033093-f10db41c-fb9b-11e7-980d-ebaee8fc2089.png)

**Comment by asparkam** [comment]
Problem in [migrationmanager/templates/create.twig line 23](https://github.com/Firstborn/Craft-CMS-Migration-Manager/blob/master/migrationmanager/templates/create.twig#L23), used `craft.sections.getAllSections()` instead of `craft.migrationManager.getAssetSources()`

**Comment by fb-derrick-grigg** [comment]
this has been fixed
