### ISSUE TITLE
Very long migration names if selected a lot of fields

### ISSUE THREAD

**Issue by asparkam** [Firstborn/Craft-CMS-Migration-Manager#19]
Migration name generates automatically, and sometimes it has a very long names more than 260 symbols (it's limit on Windows systems for example). It will be great if user will have possibility set your own name if he wants. Else name will be autogenerated.

**Comment by fb-derrick-grigg** [comment]
Long file names are a concern, however the file name is automatically trimmed down to prevent system errors when it is longer than 255 characters. I do like the idea of a adding a name field when creating migrations. Look for that in a future release.

**Comment by asparkam** [comment]
It's working in release 1.0.8.5. Thank you! Have it possibility to set names to entrys and globals migrations? May be add content migrations of Entries and Globals into "Create migration" tabs for name settings?

**Comment by dgrigg** [comment]
content migrations for entries/globals/categories use the title in the migration name. For now those migrations can only be created from the entry/global/category pages to make it easier to select the specific items you wish to create content migrations for, https://github.com/Firstborn/Craft-CMS-Migration-Manager#content-migrations
