### ISSUE TITLE
Impossible to access an attribute ("getAllGroups") on a null variable.

### ISSUE THREAD

**Issue by tomsansome** [Firstborn/Craft-CMS-Migration-Manager#2]
### Description
If I click on "Migration Manager" in the admin area, I get the following error shown here:

![Error](https://cl.ly/mxLh/[337f1b522c560c13c76ac81197bd64b2]_Screen%20Shot%202017-10-07%20at%2012.18.58.png)

`Impossible to access an attribute ("getAllGroups") on a null variable.`

I have a feeling it is to do with the fact that I have the `Personal` Craft CMS plan, which does not have user groups.

### Additional info

- Craft version: `2.6.2991`
- PHP version: `7.0.15`

**Comment by fb-derrick-grigg** [comment]
Added a check for the Craft edition to make sure it has user group support
