### ISSUE TITLE
Official support for Relabel plugin?

### ISSUE THREAD

**Issue by timeverts** [Firstborn/Craft-CMS-Migration-Manager#22]
Just wondering whether there will be any official support for the excellent [Relabel](https://straightupcraft.com/craft-plugins/relabel) plugin by @benjamminf?

With the Relabel plugin, fields in a field layout can be assigned a different display title and instructions for that field within that field layout. This allows reuse of Craft CMS fields across multiple layouts, which is great and DRY! Upon saving a field layout (fields.saveFieldLayout event), the Relabel plugin looks for a $_POST['relabel'] array that has stored the data for fields relabeled in the field layout. It then saves that data to the craft_relabel table, capturing the field id, field layout id, title and instructions assigned to the field, so it can be used later.

At the moment, the result of executing migrations created for anything with a field layout (e.g. Sections, Globals, Neo fields etc.) is that the associated Relabel data for the field layout is totally lost. This is because Craft creates a brand new field layout record every time a field layout is saved. Thus, if there was Relabel data for the original field layout (before the migration is executed), it will get removed after the migration, since the consequence of Craft purging the original field layout from the database means the associated records with the same original field layout id in the craft_relabel table are also purged. 

It would be great if the Migration Manager plugin could be modified to capture and store Relabel data at the time a migration is created. Hopefully then it you should just be able to inject that Relabel data into $_POST['relabel'] before you call save on the field layout from the migration service and all the Relabel data should be retained in the new field layout.

I was super excited about using this Migration Manager plugin, but this now creates a BIG road block!

Really hope you guys can please fix this soon.

**Comment by fb-derrick-grigg** [comment]
It's not something I had looked at but it's certainly possible. This is possible via the Field events using a custom plugin, https://github.com/Firstborn/Craft-CMS-Migration-Manager/blob/master/README.md, scroll down to the Field Type Support section

**Comment by timeverts** [comment]
@fb-derrick-grigg, thanks for your reply.

I've taken a look at your plugin code. Unfortunately, with the exception of Neo fields (they specifically use field layouts on a per field basis), I don't think using those field events would suffice. 

The reason being is that the Relabel data is not really tied to fields themselves directly, but tied to fields when they are used in the context of a particular field layout. So it would need to be possible to save or add the data for Relabelled fields when exporting or importing something that saves/creates a field layout. In your plugin this would be Global Sets, User Groups, Categories, Tags and Sections. 

If there were events raised on migration creation whenever the data for something with a field layout is captured and an event raised on migration execution just before something with a field layout is saved, then I think that should allow suitable injection for the Relablled data via a custom plugin.

As an example, in **MigrationManager_SectionsService::exportItem()** you could raise an 'onExportEntryType', something like below:

    $fieldLayout = $entryType->getFieldLayout();

    foreach ($fieldLayout->getTabs() as $tab) {
        $newEntryType['fieldLayout'][$tab->name] = [];
        foreach ($tab->getFields() as $tabField) {

            $newEntryType['fieldLayout'][$tab->name][] = craft()->fields->getFieldById($tabField->fieldId)->handle;
            if ($tabField->required) {
                $newEntryType['requiredFields'][] = craft()->fields->getFieldById($tabField->fieldId)->handle;
            }
        }
    }

    // Fire an 'onExportEntryType' event
    $event = new Event($this, [
        'section' => $section,
        'entryType' => $entryType,
        'value' => $newEntryType
    ]);
    $this->onExportEntryType($event);

    if (!$event->performAction) {
        // Don't export entry type.
        continue;
    }

    array_push($newSection['entrytypes'], $event->params['value']);

And in **MigrationManager_SectionsService::importItem()**, you could raise an 'onImportEntryType', something like below:

    //add entry types
    foreach ($data['entrytypes'] as $key => $newEntryType) {
        $existingType = $this->getSectionEntryTypeByHandle($newEntryType['handle'], $section->id);
        if ($existingType) {
            $this->mergeEntryType($newEntryType, $existingType);
        }

        // Fire an 'onImportEntryType' event
        $event = new Event($this, array(
            'section' => $section,
            'entryType' => $existingType,
            'value' => $newEntryType
        ));
        $this->onImportEntryType($event);

        if (!$event->performAction) {
            // Don't import entry type.
            continue;
        } 

        $entryType = $this->createEntryType($event->params['value'], $section);

        if (!craft()->sections->saveEntryType($entryType)) {
            $result = false;
        }
    }

You would also need to have similar events for exporting and importing Global Sets, User Groups, Categories and Tags, as these also make use of field layouts.

**Comment by fb-derrick-grigg** [comment]
@timeverts I have added export/import events to the major elements that contain field types so you can customize the migration data just before the migration is created and on the other side listen for the import event to deal with the customized data. See the https://github.com/Firstborn/Craft-CMS-Migration-Manager/blob/master/README.md for a brief example.
