### ISSUE TITLE
Craft repeatedly prompting for plugin database updates

### ISSUE THREAD

**Issue by timeverts** [Firstborn/Craft-CMS-Migration-Manager#24]
We are running a Craft CMS 2.6.3013 site.

We recently upgraded Migration Manager from version 1.0.8.5 to 1.0.8.8. Since then, at least once per day our site will go into maintenance mode (which is bad in production!). Logging into the admin dashboard, we see that Craft believes Migration Manager needs to perform a database update.

When this prompt last appeared, I checked the craft_plugins table in the database. Interestingly, it showed that the installed version of the plugin in the database record was 1.0.8.5, even though the new version of the plugin had been successfully installed many days ago and at that time the database record had updated to show 1.0.8.8 as the version.

Unfortunately I cannot provide steps to reproduce the problem, as I do not know what triggers it (perhaps a full cache clear or something). But it does seem to keep happening at least once on a daily basis.

Back in the old days, Craft used to use just the plugin version number to determine whether a database update was required for a plugin. However, this was not ideal, since it meant that every time a plugin was upgraded, Craft would attempt to look for database migrations that needed to be run even if there wasn't any in the update.  So Craft added a new method in the main plugin file called getSchemaVersion() as a way of separately tracking the database schema version for the plugin. Then, only if the schema version was updated as part of a plugin update would Craft prompt for a database update for the plugin and run the migrations associated with that update.

Now I noticed that the Migration Manager plugin does not have a getSchemaVersion() method in the main plugin class. I am thinking that perhaps if you add the getSchemaVersion() method and set the schema version to 1.0.0 it may resolve this issue.

Can you please add that in and we can report back if the problem still persists.

So it could be a bug in Craft that is causing this issue. The only other thing I can think of that is a bit unusual, is that a 4 segment version number is being used for the plugin version, whereas most developers only use 3 (major.minor.patch  e.g. 1.2.1). But please try the schema version function first.

**Comment by MatthijsKamstra** [comment]
We have a similar problem. 

We update the plugin (but also changes to craftcms) via git and push these changes to staging and later to production....
Currently we haven't activate the plugin on production because every update to the plugin sets the website in maintenance mode. And someone needs to push the button to update...

My request would be to make the update process less "aggressive" (if possible)

Besides that... this plugin makes my life much easier! thx

**Comment by fb-derrick-grigg** [comment]
@timeverts @MatthijsKamstra I will look further into this. Changing the MigrationManager version does bump Craft into maintenance mode which is a hassle. Once the plugin has been updated it should not continue to happen. Based on the note about the database not having the updated plugin version, it sounds like Craft was not correctly updating the version in the table. I will check into the schema version, that may fix the issue.

**Comment by fb-derrick-grigg** [comment]
@timeverts @MatthijsKamstra I have added the getSchemaVersion which should prevent the maintenance issue from happening (after you get updated to the new version).
