### ISSUE TITLE
Could this work with Craft Commerce?

### ISSUE THREAD

**Issue by martisj** [Firstborn/Craft-CMS-Migration-Manager#27]
Craft commerce has a concept of products and they are also regular ol' Elements. Could Migration manager be extended to include this?

**Comment by fb-derrick-grigg** [comment]
@martisj yes it certainly could be. We are deep into creating the Craft3 version right now, this is something we could add into that release.

**Comment by balintant** [comment]
It might be best to have an extendable solution, like the Payment Gateways in Commerce.
