### ISSUE TITLE
Getting a fatal error when trying to migrate entries

### ISSUE THREAD

**Issue by startingnowco** [Firstborn/Craft-CMS-Migration-Manager#33]
I was testing this plug-in by migrating some entries from a staging environment to my local environment and I got a fatal error when running the migration (see screenshot attached).

![screen shot 2018-07-02 at 11 25 45 am](https://user-images.githubusercontent.com/20543814/42172803-1d91bcb4-7deb-11e8-9648-a9af4a936f73.png)

Some notes:
+ I was trying to migrate a set of entries that had significant content updates. These entries already existed in the local environment, but their content had changed on the staging environment.
+ I selected the entries from Craft's entries list and used the new "Create migration" option in the actions menu
+ Before doing this migration, I made sure that any dependent categories, fields, assets, etc. were already in place on my local environment
+ I had run the plug-in successfully to migrate a section prior to this attempt to migrate entries. I did this from the plug-in's UI

Any ideas on what the problem could be?

**Comment by startingnowco** [comment]
Forgot to include:
Craft version: 2.6.2997
Plugin version: 1.0.9.0

**Comment by fb-derrick-grigg** [comment]
@startingnowco try the latest version, confirmed that the function exists and is being called correctly.
