### ISSUE TITLE
Does Migration Manager work with Postgres backend?

### ISSUE THREAD

**Issue by grafixgeek** [Firstborn/Craft-CMS-Migration-Manager#34]
Trying to use MM to move set up and content from a Craft 3 MySQL backend to a Postgres one. I set up small "bite-sized" migrations but none of them worked. Each one threw a different error message. I just wondered if this was expected to work?

**Comment by fb-derrick-grigg** [comment]
This plugin is for Craft 2, did you install the correct plugin?

**Comment by grafixgeek** [comment]
Right, sorry it was Craft 3 - I added the issue in wrong place. Apologies.
