### ISSUE TITLE
Make generated migrations path configurable

### ISSUE THREAD

**Issue by timeverts** [Firstborn/Craft-CMS-Migration-Manager#35]
Would it be possible to make the path for generated migrations configurable through a Craft configuration file for the plugin?

Each time we download a new version of the plugin and replace the previous migrationmanager plugin folder, we have to keep remembering to add back in the folder of generated migrations. For this reason, It would be much easier if it were possible to configure the plugin to store the generated migrations in a folder that is outside of craft/plugins/migrationmanager.

**Comment by fb-derrick-grigg** [comment]
@timeverts unfortunately that path can not be changed. The plugin source doesn't contain the migrations folder which should make updating the plugin folder quick without needing to replace the existing migrations folder. You could also try something like this https://dgrigg.com/blog/setting-up-a-craftcms-website-and-plugins-with-composer
