### ISSUE TITLE
An error was encountered

### ISSUE THREAD

**Issue by jamielaughton** [Firstborn/Craft-CMS-Migration-Manager#36]
Hi there, 

I've added a basic migration created from my 'boilerplate' craft-3 install, to a clean install of craft three. 

Every time i try to run the migration in the new install i just get 'An error was encountered. Rolling back ...' then the error stack:

Undefined
Undefined
The shell command "mysqldump --defaults-extra-file="**path to my local install**/storage/runtime/temp/my.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --set-charset --triggers --single-transaction --no-data --result-file="**path to my local install**/storage/backups/spacecentre-new_180807_090517_5x2dsn7okc_v3.0.18.sql" spacecentre-new && mysqldump --defaults-extra-file=**path to my local install**/storage/runtime/temp/my.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --set-charset --triggers --no-create-info --ignore-table=spacecentre-new.craft_assetindexdata --ignore-table=spacecentre-new.craft_assettransformindex --ignore-table=spacecentre-new.craft_cache --ignore-table=spacecentre-new.craft_sessions --ignore-table=spacecentre-new.craft_templatecaches --ignore-table=spacecentre-new.craft_templatecachecriteria --ignore-table=spacecentre-new.craft_templatecacheelements spacecentre-new >> "**path to my local install**/storage/backups/spacecentre-new_180807_090517_5x2dsn7okc_v3.0.18.sql"" failed with exit code 127: sh: mysqldump: command not found

Any help on this would be great!

Cheers,
Jamie

**Comment by fb-ziad-hilal** [comment]
This plugin is for Craft CMS 2. If you're on Craft 3, then you should try out the updated plugin: https://github.com/Firstborn/Craft-Migration-Manager

**Comment by jamielaughton** [comment]
My bad, I was meant to post this on the craft 3 plugin page. Thanks for the heads-up!
