### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by kevadamson** [Firstborn/Craft-CMS-Migration-Manager#40]
craft/plugins/migrationmanager/services/MigrationManager_MigrationsService.phpon line 642

Although reverting back to 1.0.8.8 seems to work for me ...

**Comment by dgrigg** [comment]
Check to see if you have iconv installed in PHP, https://www.php.net/manual/en/intro.iconv.php

**Comment by kevadamson** [comment]
It says: "You have a buggy version of iconv installed. (See PHP bug #48147 and iconv bug #13541)"
