### ISSUE TITLE
Possible to automatically run migrations?

### ISSUE THREAD

**Issue by paullegrand** [Firstborn/Craft-CMS-Migration-Manager#41]
Is it possible to automatically run the migrations when the migration files are committed?

We have migrations that if they're not run, they break things and cause downtime when the rest of the update is pulled in, until we can go into the control panel and manually run the migration.

**Comment by dgrigg** [comment]
You can run them using the craft cli 

./craft migrate/all

https://docs.craftcms.com/v3/extend/migrations.html#executing-migrations
