### ISSUE TITLE
Migration can not be created, when I choose more than 11 elements.

### ISSUE THREAD

**Issue by AlexandrZherdev** [Firstborn/Craft-CMS-Migration-Manager#5]
Hello.
If I choose more than 11 elements I've got next error:
![example1](https://user-images.githubusercontent.com/32765290/31540264-de620c10-b013-11e7-9f81-b6624c8e83c1.jpg)
![error-1](https://user-images.githubusercontent.com/32765290/31540365-24b99cd2-b014-11e7-8f4e-9f55c0a785a4.jpg)

May be generated name for migration file is too long?
If choose less than 11 elements it works perfect.

Addition info:
windows 10
craft 2.6.2991
php 5.5

**Comment by fb-derrick-grigg** [comment]
thanks for catching this, grab the latest and try.

**Comment by AlexandrZherdev** [comment]
Hello.
You have one mistake in MigrationManager_MigrationsService.php.
In this row "use \GuzzleHttp\Psr7\str;" you should delete first slash.
Thanks for plugin :)
