### ISSUE TITLE
Probltm with field migration (groupId)

### ISSUE THREAD

**Issue by AlexandrZherdev** [Firstborn/Craft-CMS-Migration-Manager#7]
Hello.
I faced with next problem: 
When I try upload my fields migration, system doesn't write groupId in "craft_fields" table. But it writes field groups in "craft_fieldgroups" table. But sometimes after uploading of migration some records in "craft_fields" table has groupId value.
And after that if I click settings -> fields in admin panel then I'll got next error:
![fieldserrorgroupid](https://user-images.githubusercontent.com/32765290/31769430-3a8ff052-b4dc-11e7-8ebd-0462511fd463.jpg)

**Comment by fb-derrick-grigg** [comment]
Which version of Craft are you running?

**Comment by AlexandrZherdev** [comment]
Craft 2.6.991
A little addition. I face this error when choose all fields for migration.

**Comment by fb-derrick-grigg** [comment]
If you select only a few fields does it work? Also how many fields are you selecting when it's all?

**Comment by AlexandrZherdev** [comment]
I think something wrong with fields because if I choose 3 first fields, I will get this error again.
I will try to understand what's wrong and write later.
Thanks for help.

**Comment by fb-derrick-grigg** [comment]
It sounds like a configuration/data issue with your fields. Without seeing the data being output it's hard to say.

**Comment by AlexandrZherdev** [comment]
The problem is related with relationship between "craft _fieldgroups" table and "craft_fields" table. If "fieldgroups" table will be filled then migration uploading will work perfect.
If both tables were empty and we upload our migration then migration will be uploaded and data will be writed into tables. But when we will klick settings -> fields in craft admin panel, we will get template error on the picture above.

**Comment by fb-derrick-grigg** [comment]
@AlexandrZherdev fixed this issue, please try the latest
