### ISSUE TITLE
Neo (matrix) not supported

### ISSUE THREAD

**Issue by eriweb** [Firstborn/Craft-CMS-Migration-Manager#9]
When trying to create a migration with neo matrix fields, matrix blocks are lost.

Any chance this could be an easy fix?

Neo is here: https://github.com/benjamminf/craft-neo

**Comment by fb-derrick-grigg** [comment]
@terbolous that's something we would need to look into. Stay tuned for updates.

**Comment by fb-derrick-grigg** [comment]
@terbolous checkout the latest updates for Neo support
